# Site settings
title: Yarn
description: > # this means to ignore newlines until "baseurl:"
  Fast, reliable, and secure dependency management.
baseurl: ""
url: "https://yarnpkg.com"
twitter_username: yarnpkg
github_username:  yarnpkg

###
# Hi there! I see you're trying to update the latest_version to whatever
# it currently is. Please don't worry about it, the team will handle it.
#
# If it appears to have fallen behind, then we have decided to hold it
# back for now, we have not forgotten about it.
#
# Thanks!
###
latest_version: 1.0.1
latest_rc_version: 1.0.0

# Whether to show the RC version on the site. Set this to false if the latest
# stable version is newer than the RC (ie. if an RC has not been released since
# the most recent stable version).
show_rc: false

# The versions of node that Yarn supports
# This is visible on the install page
node_support: ^4.8.0 and >= 5.7.0

gacode: "UA-85522875-1"

exclude:
  - README.md
  - crowdin.yaml
  - Gemfile
  - Gemfile.lock
  - Makefile
  - _sass/bootstrap
  - .sass-cache
  - node_modules
  - js/src

include:
  - _redirects
  - install.sh

gems:
  - jekyll-redirect-from
  - jekyll-paginate

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'rougeHighlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

sass:
  style: compressed

redcarpet:
  extensions: [with_toc_data]

# Blog Settings
permalink: /blog/:year/:month/:day/:title/
paginate: 1






# ignore me
__empty_array__: []
